In [5]:
import pandas as pd

# Cấu hình mở khóa giới hạn hàng và cột toàn cục
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Từ bây giờ cứ gọi tên biến là nó sẽ hiện ra toàn bộ
matrix = pd.read_pickle('output/interaction_matrix.pkl')
matrix

            AE2E632GMYL5U2ESNXOX5UT5D34A  AE2OFVZSIE6KSBAPG6GMKCER35LA  \
product_id
B002PD61Y4                           0.0                           0.0
B008FWZGSG                           0.0                           0.0
B00NH11KIK                           0.0                           0.0
B00NH11PEY                           0.0                           0.0
B0141EZMAI                           0.0                           0.0
B01DEWVZ2C                           0.0                           0.0
B01FSYQ2A4                           0.0                           0.0
B01GGKYKQM                           0.0                           0.0
B01GGKZ0V6                           0.0                           0.0
B01M4GGIVU                           0.0                           0.0
B07232M876                           0.0                           0.0
B077Z65HSD                           0.0                           0.0
B0789LZTCJ                           0.0                           0.0
B078G6ZF5Z                           0.0                           0.0
B07DJLFMPS                           0.0                           4.0
B07GVGTSLN                           0.0                           0.0
B07JW9H4J1                           0.0                           0.0
B07KRCW6LZ                           0.0                           0.0
B07KSMBL2H                           0.0                           0.0
B07P681N66                           0.0                           0.0
B07RD611Z8                           0.0                           0.0
B07WG8PDCW                           0.0                           0.0
B07XJYYH7L                           0.0                           0.0
B07XLCFSSN                           0.0                           0.0
B082LSVT4B                           0.0                           0.0
B082LZGK39                           0.0                           0.0
B082T6V3DT                           0.0                           0.0
B083342NKJ                           0.0                           0.0
B085194JFL                           0.0                           0.0
B085DTN6R2                           0.0                           0.0
B085HY1DGR                           0.0                           0.0
B08BCKN299                           0.0                           0.0
B08CDKQ8T6                           0.0                           0.0
B08CF3B7N1                           0.0                           0.0
B08CF3D7QR                           0.0                           0.0
B08DDRGWTJ                           0.0                           0.0
B08DPLCM6T                           0.0                           0.0
B08HDJ86NZ                           0.0                           0.0
B08K4PSZ3V                           0.0                           0.0
B08MTCKDYN                           0.0                           0.0
B08QSC1XY8                           0.0                           0.0
B08R69VDHT                           0.0                           0.0
B08WRBG3XW                           0.0                           0.0
B08WRWPM22                           0.0                           0.0
B08Y1SJVV5                           0.0                           0.0
B08Y1TFSP6                           0.0                           0.0
B0949SBKMP                           0.0                           0.0
B094JNXNPV                           4.0                           0.0
B094YFFSMY                           0.0                           0.0
B096MSW6CT                           0.0                           0.0
B096VF5YYF                           0.0                           0.0
B097R25DP7                           0.0                           0.0
B098NS6PVG                           0.0                           0.0
B0994GFWBH                           0.0                           0.0
B09C6HWG18                           0.0                           0.0
B09C6HXFC1                           0.0                           0.0
B09CMM3VGK                           0.0                           0.0
B09CMP1SC8                           0.0                           0.0
B09F6S8BT6                           0.0                           0.0
B09F9YQQ7B                           0.0                           0.0
B09KGV7WSV                           0.0                           0.0
B09KLVMZ3B                           0.0                           0.0
B09MQSCJQ1                           0.0                           0.0
B09MT84WV5                           0.0                           0.0
B09NHVCHS9                           0.0                           0.0
B09NVPSCQT                           0.0                           0.0
B09Q8HMKZX                           0.0                           0.0
B09RWZRCP1                           0.0                           0.0
B09RZS1NQT                           0.0                           0.0
B09V12K8NT                           0.0                           0.0
B09W5XR9RT                           0.0                           0.0
B09YLXYP7Y                           0.0                           0.0
B09YV4MW2T                           0.0                           0.0
B09YV4RG4D                           0.0                           0.0
B09Z6WH2N1                           0.0                           0.0
B09ZQK9X8G                           0.0                           0.0
B0B2DJDCPX                           0.0                           0.0
B0B3MWYCHQ                           0.0                           0.0
B0B3N7LR6K                           0.0                           0.0
B0B3RRWSF6                           0.0                           0.0
B0B4DT8MKT                           0.0                           0.0
B0B4HJNPV4                           0.0                           0.0
B0B5B6PQCT                           0.0                           0.0
B0B5LVS732                           0.0                           0.0
B0B5ZF3NRK                           0.0                           0.0
B0B86CDHL1                           0.0                           0.0
B0B9BD2YL4                           0.0                           0.0
B0B9BXKBC7                           0.0                           0.0
B0BDRVFDKP                           0.0                           0.0
B0BFWGBX61                           0.0                           0.0
B0BMXMLSMM                           0.0                           0.0

            AE33MAZWYRVAAICGNACZAIWACK7Q  AE3D5CJ2GDUP5SQ3AAYMVAGDTX7A  \
product_id
B002PD61Y4                           0.0                           0.0
B008FWZGSG                           0.0                           0.0
B00NH11KIK                           0.0                           0.0
B00NH11PEY                           0.0                           0.0
B0141EZMAI                           0.0                           0.0
B01DEWVZ2C                           0.0                           0.0
B01FSYQ2A4                           0.0                           0.0
B01GGKYKQM                           0.0                           0.0
B01GGKZ0V6                           0.0                           0.0
B01M4GGIVU                           0.0                           0.0
B07232M876                           0.0                           0.0
B077Z65HSD                           0.0                           0.0
B0789LZTCJ                           0.0                           0.0
B078G6ZF5Z                           0.0                           0.0
B07DJLFMPS                           0.0                           0.0
B07GVGTSLN                           0.0                           0.0
B07JW9H4J1                           0.0                           0.0
B07KRCW6LZ                           0.0                           0.0
B07KSMBL2H                           0.0                           4.4
B07P681N66                           0.0                           0.0
B07RD611Z8                           4.1                           0.0
B07WG8PDCW                           0.0                           0.0
B07XJYYH7L                           0.0                           0.0
B07XLCFSSN                           0.0                           0.0
B082LSVT4B                           0.0                           0.0
B082LZGK39                           0.0                           0.0
B082T6V3DT                           0.0                           0.0
B083342NKJ                           0.0                           0.0
B085194JFL                           0.0                           0.0
B085DTN6R2                           0.0                           0.0
B085HY1DGR                           0.0                           0.0
B08BCKN299                           0.0                           0.0
B08CDKQ8T6                           0.0                           0.0
B08CF3B7N1                           0.0                           0.0
B08CF3D7QR                           0.0                           0.0
B08DDRGWTJ                           0.0                           0.0
B08DPLCM6T                           0.0                           0.0
B08HDJ86NZ                           0.0                           0.0
B08K4PSZ3V                           0.0                           0.0
B08MTCKDYN                           0.0                           0.0
B08QSC1XY8                           0.0                           0.0
B08R69VDHT                           0.0                           0.0
B08WRBG3XW                           0.0                           0.0
B08WRWPM22                           0.0                           0.0
B08Y1SJVV5                           0.0                           0.0
B08Y1TFSP6                           0.0                           0.0
B0949SBKMP                           0.0                           0.0
B094JNXNPV                           0.0                           0.0
B094YFFSMY                           0.0                           0.0
B096MSW6CT                           0.0                           0.0
B096VF5YYF                           0.0                           0.0
B097R25DP7                           0.0                           0.0
B098NS6PVG                           0.0                           0.0
B0994GFWBH                           0.0                           0.0
B09C6HWG18                           0.0                           0.0
B09C6HXFC1                           0.0                           0.0
B09CMM3VGK                           0.0                           0.0
B09CMP1SC8                           0.0                           0.0
B09F6S8BT6                           0.0                           0.0
B09F9YQQ7B                           0.0                           0.0
B09KGV7WSV                           0.0                           0.0
B09KLVMZ3B                           0.0                           0.0
B09MQSCJQ1                           0.0                           0.0
B09MT84WV5                           0.0                           0.0
B09NHVCHS9                           0.0                           0.0
B09NVPSCQT                           0.0                           0.0
B09Q8HMKZX                           0.0                           0.0
B09RWZRCP1                           0.0                           0.0
B09RZS1NQT                           0.0                           0.0
B09V12K8NT                           0.0                           0.0
B09W5XR9RT                           0.0                           0.0
B09YLXYP7Y                           0.0                           0.0
B09YV4MW2T                           0.0                           0.0
B09YV4RG4D                           0.0                           0.0
B09Z6WH2N1                           0.0                           0.0
B09ZQK9X8G                           0.0                           0.0
B0B2DJDCPX                           0.0                           0.0
B0B3MWYCHQ                           0.0                           0.0
B0B3N7LR6K                           0.0                           0.0
B0B3RRWSF6                           0.0                           0.0
B0B4DT8MKT                           0.0                           0.0
B0B4HJNPV4                           0.0                           0.0
B0B5B6PQCT                           0.0                           0.0
B0B5LVS732                           0.0                           0.0
B0B5ZF3NRK                           0.0                           0.0
B0B86CDHL1                           0.0                           0.0
B0B9BD2YL4                           0.0                           0.0
B0B9BXKBC7                           0.0                           0.0
B0BDRVFDKP                           0.0                           0.0
B0BFWGBX61                           0.0                           0.0
B0BMXMLSMM                           0.0                           0.0

            AE3MQNNHHLUHXURL5S7IAR7JTGNQ  AE3O6366WGEQAANKJ76QETTUQQTQ  \
product_id
B002PD61Y4                           0.0                           0.0
B008FWZGSG                           0.0                           0.0
B00NH11KIK                           0.0                           0.0
B00NH11PEY                           0.0                           0.0
B0141EZMAI                           0.0                           0.0
B01DEWVZ2C                           0.0                           0.0
B01FSYQ2A4                           0.0                           0.0
B01GGKYKQM                           0.0                           0.0
B01GGKZ0V6                           0.0                           0.0
B01M4GGIVU                           0.0                           0.0
B07232M876                           0.0                           0.0
B077Z65HSD                           0.0                           0.0
B0789LZTCJ                           0.0                           0.0
B078G6ZF5Z                           0.0                           0.0
B07DJLFMPS                           0.0                           0.0
B07GVGTSLN                           0.0                           0.0
B07JW9H4J1                           0.0                           0.0
B07KRCW6LZ                           0.0                           0.0
B07KSMBL2H                           0.0                           4.4
B07P681N66                           0.0                           0.0
B07RD611Z8                           0.0                           0.0
B07WG8PDCW                           0.0                           0.0
B07XJYYH7L                           0.0                           0.0
B07XLCFSSN                           0.0                           0.0
B082LSVT4B                           0.0                           0.0
B082LZGK39                           0.0                           0.0
B082T6V3DT                           0.0                           0.0
B083342NKJ                           0.0                           0.0
B085194JFL                           0.0                           0.0
B085DTN6R2                           0.0                           0.0
B085HY1DGR                           0.0                           0.0
B08BCKN299                           0.0                           0.0
B08CDKQ8T6                           0.0                           0.0
B08CF3B7N1                           4.2                           0.0
B08CF3D7QR                           0.0                           0.0
B08DDRGWTJ                           0.0                           0.0
B08DPLCM6T                           0.0                           0.0
B08HDJ86NZ                           0.0                           0.0
B08K4PSZ3V                           0.0                           0.0
B08MTCKDYN                           0.0                           0.0
B08QSC1XY8                           0.0                           0.0
B08R69VDHT                           0.0                           0.0
B08WRBG3XW                           0.0                           0.0
B08WRWPM22                           0.0                           0.0
B08Y1SJVV5                           0.0                           0.0
B08Y1TFSP6                           0.0                           0.0
B0949SBKMP                           0.0                           0.0
B094JNXNPV                           0.0                           0.0
B094YFFSMY                           0.0                           0.0
B096MSW6CT                           0.0                           0.0
B096VF5YYF                           0.0                           0.0
B097R25DP7                           0.0                           0.0
B098NS6PVG                           0.0                           0.0
B0994GFWBH                           0.0                           0.0
B09C6HWG18                           0.0                           0.0
B09C6HXFC1                           0.0                           0.0
B09CMM3VGK                           0.0                           0.0
B09CMP1SC8                           0.0                           0.0
B09F6S8BT6                           0.0                           0.0
B09F9YQQ7B                           0.0                           0.0
B09KGV7WSV                           0.0                           0.0
B09KLVMZ3B                           0.0                           0.0
B09MQSCJQ1                           0.0                           0.0
B09MT84WV5                           0.0                           0.0
B09NHVCHS9                           0.0                           0.0
B09NVPSCQT                           0.0                           0.0
B09Q8HMKZX                           0.0                           0.0
B09RWZRCP1                           0.0                           0.0
B09RZS1NQT                           0.0                           0.0
B09V12K8NT                           0.0                           0.0
B09W5XR9RT                           0.0                           0.0
B09YLXYP7Y                           0.0                           0.0
B09YV4MW2T                           0.0                           0.0
B09YV4RG4D                           0.0                           0.0
B09Z6WH2N1                           0.0                           0.0
B09ZQK9X8G                           0.0                           0.0
B0B2DJDCPX                           0.0                           0.0
B0B3MWYCHQ                           0.0                           0.0
B0B3N7LR6K                           0.0                           0.0
B0B3RRWSF6                           0.0                           0.0
B0B4DT8MKT                           0.0                           0.0
B0B4HJNPV4                           0.0                           0.0
B0B5B6PQCT                           0.0                           0.0
B0B5LVS732                           0.0                           0.0
B0B5ZF3NRK                           0.0                           0.0
B0B86CDHL1                           0.0                           0.0
B0B9BD2YL4                           0.0                           0.0
B0B9BXKBC7                           0.0                           0.0
B0BDRVFDKP                           0.0                           0.0
B0BFWGBX61                           0.0                           0.0
B0BMXMLSMM                           0.0                           0.0

            AE3Q6KSUK5P75D5HFYHCRAOLODSA  AE43KS43Y6L62UBGG6K64AD5OISA  \
product_id
B002PD61Y4                           0.0                           0.0
B008FWZGSG                           0.0                           0.0
B00NH11KIK                           0.0                           0.0

In [7]:
import pandas as pd

# Đường dẫn đến file mapping
file_path = 'output/item_mapping.pkl'

# Đọc file
mapping = pd.read_pickle(file_path)

print("Kiểu dữ liệu gốc:", type(mapping))
print(f"Tổng số sản phẩm có trong dữ liệu: {len(mapping)}")

# Ép kiểu sang DataFrame để có giao diện bảng đẹp mắt
view_df = pd.Series(mapping).to_frame(name="Tên Sản Phẩm")
view_df.index.name = "Mã Sản Phẩm (ID)"

with pd.option_context('display.max_rows', None):
    display(view_df)

Kiểu dữ liệu gốc: <class 'dict'>
Tổng số sản phẩm có trong dữ liệu: 91

                                                       Tên Sản Phẩm
Mã Sản Phẩm (ID)
B07JW9H4J1        Wayona Nylon Braided USB to Lightning Fast Cha...
B098NS6PVG        Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
B096MSW6CT        Sounce Fast Phone Charging Cable & Data Sync U...
B08HDJ86NZ        boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
B08CF3B7N1        Portronics Konnect L 1.2M Fast Charging 3A 8 P...
B08Y1TFSP6        pTron Solero TB301 3A Type-C Data and Fast Cha...
B08WRWPM22        boAt Micro USB 55 Tangle-free, Sturdy Micro US...
B08DDRGWTJ                   MI Usb Type-C Cable Smartphone (Black)
B082LZGK39        Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
B08CF3D7QR        Portronics Konnect L POR-1081 Fast Charging 3A...
B0789LZTCJ        boAt Rugged v3 Extra Tough Unbreakable Braided...
B07KSMBL2H        AmazonBasics Flexible Premium HDMI Cable (Blac...
B085DTN6R2        Portronics Konnect CL 20W POR-1067 Type-C to 8...
B09KLVMZ3B        Portronics Konnect L 1.2M POR-1401 Fast Chargi...
B083342NKJ        MI Braided USB Type-C Cable for Charging Adapt...
B082LSVT4B        Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
B08WRBG3XW        boAt Type C A325 Tangle-free, Sturdy Type C Ca...
B08DPLCM6T        LG 80 cm (32 inches) HD Ready Smart LED TV 32L...
B09C6HXFC1        Duracell USB Lightning Apple Certified (Mfi) B...
B085194JFL        tizum HDMI to VGA Adapter Cable 1080P for Proj...
B09F6S8BT6        Samsung 80 cm (32 Inches) Wondertainment Serie...
B09NHVCHS9              Flix Micro Usb Cable For Smartphone (Black)
B01M4GGIVU        Tizum High Speed HDMI Cable with Ethernet | Su...
B094JNXNPV        Ambrane Unbreakable 3 in 1 Fast Charging Braid...
B09W5XR9RT        Duracell USB C To Lightning Apple Certified (M...
B077Z65HSD        boAt A400 USB Type-C to USB-A 2.0 Male Data Ca...
B00NH11PEY        AmazonBasics USB 2.0 - A-Male to A-Female Exte...
B09CMM3VGK        Ambrane 60W / 3A Type C Fast Charging Unbreaka...
B08QSC1XY8        Zoul USB C 60W Fast Charging 3A 6ft/2M Long Ty...
B008FWZGSG        Samsung Original Type C to C Cable - 3.28 Feet...
B0B4HJNPV4        pTron Solero T351 3.5Amps Fast Charging Type-C...
B08Y1SJVV5        pTron Solero MB301 3A Micro USB Data & Chargin...
B07XLCFSSN        Amazonbasics Nylon Braided Usb-C To Lightning ...
B09RZS1NQT        Sounce 65W OnePlus Dash Warp Charge Cable, 6.5...
B09C6HWG18        Duracell Type C To Type C 5A (100W) Braided Sy...
B00NH11KIK        AmazonBasics USB 2.0 Cable - A-Male to B-Male ...
B07KRCW6LZ        TP-Link Nano AC600 USB Wi-Fi Adapter(Archer T2...
B07XJYYH7L        Wecool Nylon Braided Multifunction Fast Chargi...
B002PD61Y4        D-Link DWA-131 300 Mbps Wireless Nano USB Adap...
B07232M876        Amazonbasics Micro Usb Fast Charging Cable For...
B07P681N66        TP-Link AC600 600 Mbps WiFi Wireless Network U...
B082T6V3DT        AmazonBasics New Release Nylon USB-A to Lightn...
B0BFWGBX61        Ambrane Unbreakable 3A Fast Charging Braided T...
B0B4DT8MKT        Wecool Unbreakable 3 in 1 Charging Cable with ...
B08CDKQ8T6        Portronics Konnect L 1.2Mtr, Fast Charging 3A ...
B0994GFWBH        Lapster 1.5 mtr USB 2.0 Type A Male to USB A M...
B01GGKZ0V6        AmazonBasics USB Type-C to USB Type-C 2.0 Cabl...
B09F9YQQ7B        Redmi 80 cm (32 inches) Android 11 Series HD R...
B09Q8HMKZX        Portronics Konnect L 20W PD Quick Charge Type-...
B01GGKYKQM        Amazon Basics USB Type-C to USB-A 2.0 Male Fas...
B0B86CDHL1        oraimo 65W Type C to C Fast Charging Cable USB...
B0B5ZF3NRK        CEDO 65W OnePlus Dash Warp Charge Cable, USB A...
B08R69VDHT        Pinnaclz Original Combo of 2 Micro USB Fast Ch...
B09RWZRCP1        boAt Type C A750 Stress Resistant, Tangle-free...
B09CMP1SC8        Ambrane 2 in 1 Type-C & Micro USB Cable with 6...
B09YLXYP7Y        Ambrane 60W / 3A Fast Charging Output Cable wi...
B0B2DJDCPX        SWAPKART Fast Charging Cable and Data Sync USB...
B07GVGTSLN        Wayona Usb Type C Fast Charger Cable Fast Char...
B0BMXMLSMM        Lapster 65W compatible for OnePlus Dash Warp C...
B0141EZMAI        Gizga Essentials USB WiFi Adapter for PC, 150 ...
B0B3RRWSF6        Fire-Boltt Phoenix Smart Watch with Bluetooth ...
B0B5B6PQCT        boAt Wave Call Smart Watch, Smart Talk with Ad...
B0BDRVFDKP        SanDisk Ultra® microSDXC™ UHS-I Card, 64GB, 14...
B0B5LVS732        Noise Pulse Go Buzz Smart Watch Bluetooth Call...
B09V12K8NT        boAt Wave Lite Smartwatch with 1.69" HD Displa...
B01DEWVZ2C        JBL C100SI Wired In Ear Headphones with Mic, J...
B07WG8PDCW        pTron Bullet Pro 36W PD Quick Charger, 3 Port ...
B09NVPSCQT        Noise ColorFit Pulse Grand Smart Watch with 1....
B09YV4RG4D        Fire-Boltt Ninja 3 Smartwatch Full Touch 1.69 ...
B09YV4MW2T        Fire-Boltt India's No 1 Smartwatch Brand Talk ...
B0B3N7LR6K        Fire-Boltt Visionary 1.78" AMOLED Bluetooth Ca...
B09ZQK9X8G        Noise ColorFit Pro 4 Advanced Bluetooth Callin...
B09MQSCJQ1        boAt Xtend Smartwatch with Alexa Built-in, 1.6...
B094YFFSMY        Tygot Bluetooth Extendable Selfie Sticks with ...
B09MT84WV5        Samsung EVO Plus 128GB microSDXC UHS-I U3 130M...
B085HY1DGR        Sounce Spiral Charger Cable Protector Data Cab...
B07RD611Z8        Ambrane 20000mAh Power Bank with 20W Fast Char...
B096VF5YYF        boAt Xtend Smartwatch with Alexa Built-in, 1.6...
B08MTCKDYN        Gizga Essentials Spiral Cable Protector Cord S...
B07DJLFMPS        HP 32GB Class 10 MicroSD Memory Card (U1 TF Ca...
B097R25DP7        Noise ColorFit Pulse Smartwatch with 3.56 cm (...
B09KGV7WSV        KINGONE Upgraded Stylus Pen, iPad Pencil, Ultr...
B0B3MWYCHQ        Fire-Boltt Ring 3 Smart Watch 1.8 Biggest Disp...
B08K4PSZ3V        Tukzer Capacitive Stylus Pen for Touch Screens...
B09Z6WH2N1        STRIFF 12 Pieces Highly Flexible Silicone Micr...
B0949SBKMP        boAt Flash Edition Smart Watch with Activity T...
B01FSYQ2A4        boAt Rockerz 400 Bluetooth On Ear Headphones W...
B08BCKN299        Sounce Gold Plated 3.5 mm Headphone Splitter f...
B078G6ZF5Z        Oraimo 18W USB & Type-C Dual Output Super Fast...
B0B9BXKBC7        WeCool S5 Long Selfie Stick, with Large Reinfo...
B0B9BD2YL4        KINGONE Wireless Charging Pencil (2nd Generati...

In [8]:
import pandas as pd

# Đường dẫn đến file
file_path = 'output/similarity_matrix.pkl'

# Đọc file pkl siêu nhanh bằng Pandas
data = pd.read_pickle(file_path)

# Kiểm tra kích thước ma trận
print(f"Kích thước ma trận tương đồng: {data.shape[0]} sản phẩm × {data.shape[1]} sản phẩm")

# MẸO: Mở khóa giới hạn cả số HÀNG và số CỘT để hiển thị toàn bộ ma trận 91x91
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(data)

Kích thước ma trận tương đồng: 91 sản phẩm × 91 sản phẩm

product_id,B002PD61Y4,B008FWZGSG,B00NH11KIK,B00NH11PEY,B0141EZMAI,B01DEWVZ2C,B01FSYQ2A4,B01GGKYKQM,B01GGKZ0V6,B01M4GGIVU,B07232M876,B077Z65HSD,B0789LZTCJ,B078G6ZF5Z,B07DJLFMPS,B07GVGTSLN,B07JW9H4J1,B07KRCW6LZ,B07KSMBL2H,B07P681N66,B07RD611Z8,B07WG8PDCW,B07XJYYH7L,B07XLCFSSN,B082LSVT4B,B082LZGK39,B082T6V3DT,B083342NKJ,B085194JFL,B085DTN6R2,B085HY1DGR,B08BCKN299,B08CDKQ8T6,B08CF3B7N1,B08CF3D7QR,B08DDRGWTJ,B08DPLCM6T,B08HDJ86NZ,B08K4PSZ3V,B08MTCKDYN,B08QSC1XY8,B08R69VDHT,B08WRBG3XW,B08WRWPM22,B08Y1SJVV5,B08Y1TFSP6,B0949SBKMP,B094JNXNPV,B094YFFSMY,B096MSW6CT,B096VF5YYF,B097R25DP7,B098NS6PVG,B0994GFWBH,B09C6HWG18,B09C6HXFC1,B09CMM3VGK,B09CMP1SC8,B09F6S8BT6,B09F9YQQ7B,B09KGV7WSV,B09KLVMZ3B,B09MQSCJQ1,B09MT84WV5,B09NHVCHS9,B09NVPSCQT,B09Q8HMKZX,B09RWZRCP1,B09RZS1NQT,B09V12K8NT,B09W5XR9RT,B09YLXYP7Y,B09YV4MW2T,B09YV4RG4D,B09Z6WH2N1,B09ZQK9X8G,B0B2DJDCPX,B0B3MWYCHQ,B0B3N7LR6K,B0B3RRWSF6,B0B4DT8MKT,B0B4HJNPV4,B0B5B6PQCT,B0B5LVS732,B0B5ZF3NRK,B0B86CDHL1,B0B9BD2YL4,B0B9BXKBC7,B0BDRVFDKP,B0BFWGBX61,B0BMXMLSMM
product_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
B002PD61Y4,1.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B008FWZGSG,0.0,1.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B00NH11KIK,0.0,0.0,1.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B00NH11PEY,0.0,0.0,0.0,1.000,0.0,0.0,0.0,0.0,0.0,0.0,0.125,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B0141EZMAI,0.0,0.0,0.0,0.000,1.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B01DEWVZ2C,0.0,0.0,0.0,0.000,0.0,1.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B01FSYQ2A4,0.0,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B01GGKYKQM,0.0,0.0,0.0,0.000,0.0,0.0,0.0,1.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B01GGKZ0V6,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,1.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B01M4GGIVU,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B07232M876,0.0,0.0,0.0,0.125,0.0,0.0,0.0,0.0,0.0,0.0,1.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B077Z65HSD,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,1.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B0789LZTCJ,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,1.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B078G6ZF5Z,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,1.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B07DJLFMPS,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,1.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B07GVGTSLN,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B07JW9H4J1,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B07KRCW6LZ,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B07KSMBL2H,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B07P681N66,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B07RD611Z8,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B07WG8PDCW,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B07XJYYH7L,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B07XLCFSSN,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B082LSVT4B,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B082LZGK39,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B082T6V3DT,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B083342NKJ,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B085194JFL,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B085DTN6R2,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B085HY1DGR,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08BCKN299,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08CDKQ8T6,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08CF3B7N1,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08CF3D7QR,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08DDRGWTJ,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08DPLCM6T,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08HDJ86NZ,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,1.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08K4PSZ3V,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08MTCKDYN,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08QSC1XY8,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08R69VDHT,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08WRBG3XW,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08WRWPM22,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08Y1SJVV5,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B08Y1TFSP6,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B0949SBKMP,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
B094JNXNPV,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0